#!/usr/bin/env bash
set -xeuo pipefail

CLANG="clang${CLANG_SUFFIX:-}"

src="${1}"
out="`basename "${1}" .c`".out
if [ ! -e "${out}" -o "${src}" -nt "${out}" ]; then
  "${CLANG}" -std=c11 -pedantic -Wall -Wextra -Werror -g "${src}" -o "${out}"
fi
exec ./"${out}" "${@:2}"
