#!/usr/bin/env bash
set -xeuo pipefail

CLANG_FORMAT="clang-format${CLANG_SUFFIX:-}"

if git status > /dev/null 2>&1; then
  cd "$(git rev-parse --show-toplevel)"
  git ls-files --modified --other | grep ".*\.\(c\|h\|cpp\|hpp\)"
  git ls-files --modified --other -z | grep -z ".*\.\(c\|h\|cpp\|hpp\)" \
    | xargs -0 "${CLANG_FORMAT}" -i -style=Google
fi
