#!/usr/bin/env bash
set -xeuo pipefail

GCC="gcc${GCC_SUFFIX:-}"
GPP="g++${GCC_SUFFIX:-}"

CC=`which "${GCC}"` CXX=`which "${GPP}"` CMAKE_PREFIX_PATH=/home/tlo/sdt/Qt/5.10.1/gcc_64 exec cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug "$@"
