#!/usr/bin/env bash
set -euo pipefail

GREP=grep
if [ "$(uname -s)" = "FreeBSD" ]; then
  # instead of /usr/bin/grep, use the grep from the gnugrep package which is
  # newer and supports more features
  GREP=/usr/local/bin/grep
fi

set -x

# grep that behaves more like ack
exec $GREP -rnI --color=auto --exclude-dir=.git "$@"
