#!/usr/bin/env bash
set -euo pipefail

SCAN_BUILD=scan-build
if [ "$(uname -o)" = "FreeBSD" ]; then
  # programs from the llvm60 package have names suffixed with "60"
  SCAN_BUILD=scan-build60
fi

set -x

exec $SCAN_BUILD tlo-make "$@"
