#!/usr/bin/env bash
set -xeuo pipefail

# run in directory with *.gcno and *.gcda files
lcov --capture --directory . --output-file coverage.info
genhtml coverage.info --output-directory coverage
firefox coverage/index.html
