#!/usr/bin/env bash
set -xeuo pipefail

CLANG_FORMAT="clang-format${CLANG_SUFFIX:-}"

find . \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \)
sleep 10

find . \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) -print0 | xargs -0 "${CLANG_FORMAT}" -i -style=Google
