#!/usr/bin/env bash
set -xeuo pipefail

CLANG="clang${CLANG_SUFFIX:-}"
CLANGPP="clang++${CLANG_SUFFIX:-}"

CC=`which "${CLANG}"` CXX=`which "${CLANGPP}"` exec cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug "$@"
