#!/usr/bin/env bash
set -xeuo pipefail

if [ $# -eq 0 ]; then
  echo "usage: `basename "${0}"` [arguments-to-flawfinder] <source-directory>"
  exit 1
fi

exec flawfinder --html --context "$@" > flawfinder-report.html
